// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace cfg
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ActionValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static ActionValue GetRootAsActionValue(ByteBuffer _bb) { return GetRootAsActionValue(_bb, new ActionValue()); }
  public static ActionValue GetRootAsActionValue(ByteBuffer _bb, ActionValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ActionValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int V { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<cfg.ActionValue> CreateActionValue(FlatBufferBuilder builder,
      int v = 0) {
    builder.StartTable(1);
    ActionValue.AddV(builder, v);
    return ActionValue.EndActionValue(builder);
  }

  public static void StartActionValue(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddV(FlatBufferBuilder builder, int v) { builder.AddInt(0, v, 0); }
  public static Offset<cfg.ActionValue> EndActionValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<cfg.ActionValue>(o);
  }
}


static public class ActionValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*V*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
