// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace cfg
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Attr : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Attr GetRootAsAttr(ByteBuffer _bb) { return GetRootAsAttr(_bb, new Attr()); }
  public static Attr GetRootAsAttr(ByteBuffer _bb, Attr obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Attr __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int VFinal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int VBase { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int VAffect { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PAffect { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool Dirty { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<cfg.Attr> CreateAttr(FlatBufferBuilder builder,
      int v_final = 0,
      int v_base = 0,
      int v_affect = 0,
      int p_affect = 0,
      bool dirty = false) {
    builder.StartTable(5);
    Attr.AddPAffect(builder, p_affect);
    Attr.AddVAffect(builder, v_affect);
    Attr.AddVBase(builder, v_base);
    Attr.AddVFinal(builder, v_final);
    Attr.AddDirty(builder, dirty);
    return Attr.EndAttr(builder);
  }

  public static void StartAttr(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddVFinal(FlatBufferBuilder builder, int vFinal) { builder.AddInt(0, vFinal, 0); }
  public static void AddVBase(FlatBufferBuilder builder, int vBase) { builder.AddInt(1, vBase, 0); }
  public static void AddVAffect(FlatBufferBuilder builder, int vAffect) { builder.AddInt(2, vAffect, 0); }
  public static void AddPAffect(FlatBufferBuilder builder, int pAffect) { builder.AddInt(3, pAffect, 0); }
  public static void AddDirty(FlatBufferBuilder builder, bool dirty) { builder.AddBool(4, dirty, false); }
  public static Offset<cfg.Attr> EndAttr(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<cfg.Attr>(o);
  }
}


static public class AttrVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*VFinal*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*VBase*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*VAffect*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PAffect*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Dirty*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
