// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace cfg
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Attr : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static Attr GetRootAsAttr(ByteBuffer _bb) { return GetRootAsAttr(_bb, new Attr()); }
  public static Attr GetRootAsAttr(ByteBuffer _bb, Attr obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Attr __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Value { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BaseValue { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int ValueAffect { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int PercentAffect { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool Dirty { get { int o = __p.__offset(12); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<cfg.Attr> CreateAttr(FlatBufferBuilder builder,
      int value = 0,
      int base_value = 0,
      int value_affect = 0,
      int percent_affect = 0,
      bool dirty = false) {
    builder.StartTable(5);
    Attr.AddPercentAffect(builder, percent_affect);
    Attr.AddValueAffect(builder, value_affect);
    Attr.AddBaseValue(builder, base_value);
    Attr.AddValue(builder, value);
    Attr.AddDirty(builder, dirty);
    return Attr.EndAttr(builder);
  }

  public static void StartAttr(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddValue(FlatBufferBuilder builder, int value) { builder.AddInt(0, value, 0); }
  public static void AddBaseValue(FlatBufferBuilder builder, int baseValue) { builder.AddInt(1, baseValue, 0); }
  public static void AddValueAffect(FlatBufferBuilder builder, int valueAffect) { builder.AddInt(2, valueAffect, 0); }
  public static void AddPercentAffect(FlatBufferBuilder builder, int percentAffect) { builder.AddInt(3, percentAffect, 0); }
  public static void AddDirty(FlatBufferBuilder builder, bool dirty) { builder.AddBool(4, dirty, false); }
  public static Offset<cfg.Attr> EndAttr(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<cfg.Attr>(o);
  }
}


static public class AttrVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Value*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*BaseValue*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*ValueAffect*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*PercentAffect*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Dirty*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
