// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace cfg
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AttrGroup : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static AttrGroup GetRootAsAttrGroup(ByteBuffer _bb) { return GetRootAsAttrGroup(_bb, new AttrGroup()); }
  public static AttrGroup GetRootAsAttrGroup(ByteBuffer _bb, AttrGroup obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AttrGroup __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Atk { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Def { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Hp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Energy { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<cfg.AttrGroup> CreateAttrGroup(FlatBufferBuilder builder,
      int atk = 0,
      int def = 0,
      int hp = 0,
      int energy = 0) {
    builder.StartTable(4);
    AttrGroup.AddEnergy(builder, energy);
    AttrGroup.AddHp(builder, hp);
    AttrGroup.AddDef(builder, def);
    AttrGroup.AddAtk(builder, atk);
    return AttrGroup.EndAttrGroup(builder);
  }

  public static void StartAttrGroup(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddAtk(FlatBufferBuilder builder, int atk) { builder.AddInt(0, atk, 0); }
  public static void AddDef(FlatBufferBuilder builder, int def) { builder.AddInt(1, def, 0); }
  public static void AddHp(FlatBufferBuilder builder, int hp) { builder.AddInt(2, hp, 0); }
  public static void AddEnergy(FlatBufferBuilder builder, int energy) { builder.AddInt(3, energy, 0); }
  public static Offset<cfg.AttrGroup> EndAttrGroup(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<cfg.AttrGroup>(o);
  }
}


static public class AttrGroupVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Atk*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Def*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Hp*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Energy*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
