// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UIDocument.Script.Core.FBS
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FBS_MoveComponent : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FBS_MoveComponent GetRootAsFBS_MoveComponent(ByteBuffer _bb) { return GetRootAsFBS_MoveComponent(_bb, new FBS_MoveComponent()); }
  public static FBS_MoveComponent GetRootAsFBS_MoveComponent(ByteBuffer _bb, FBS_MoveComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBS_MoveComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UIDocument.Script.Core.FBS.FBS_ActionValue? CurrentAction { get { int o = __p.__offset(4); return o != 0 ? (UIDocument.Script.Core.FBS.FBS_ActionValue?)(new UIDocument.Script.Core.FBS.FBS_ActionValue()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public UIDocument.Script.Core.FBS.FBS_ActionValue? MaxAction { get { int o = __p.__offset(6); return o != 0 ? (UIDocument.Script.Core.FBS.FBS_ActionValue?)(new UIDocument.Script.Core.FBS.FBS_ActionValue()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public UIDocument.Script.Core.FBS.FBS_Speed? Speed { get { int o = __p.__offset(8); return o != 0 ? (UIDocument.Script.Core.FBS.FBS_Speed?)(new UIDocument.Script.Core.FBS.FBS_Speed()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public int Position { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Dmg { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static void StartFBS_MoveComponent(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddCurrentAction(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_ActionValue> currentActionOffset) { builder.AddStruct(0, currentActionOffset.Value, 0); }
  public static void AddMaxAction(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_ActionValue> maxActionOffset) { builder.AddStruct(1, maxActionOffset.Value, 0); }
  public static void AddSpeed(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_Speed> speedOffset) { builder.AddStruct(2, speedOffset.Value, 0); }
  public static void AddPosition(FlatBufferBuilder builder, int position) { builder.AddInt(3, position, 0); }
  public static void AddDmg(FlatBufferBuilder builder, int dmg) { builder.AddInt(4, dmg, 0); }
  public static Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent> EndFBS_MoveComponent(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent>(o);
  }
}


static public class FBS_MoveComponentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CurrentAction*/, 4 /*UIDocument.Script.Core.FBS.FBS_ActionValue*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*MaxAction*/, 4 /*UIDocument.Script.Core.FBS.FBS_ActionValue*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Speed*/, 4 /*UIDocument.Script.Core.FBS.FBS_Speed*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*Position*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*Dmg*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
