// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace UIDocument.Script.Core.FBS
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FBS_MoveComponentStream : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static FBS_MoveComponentStream GetRootAsFBS_MoveComponentStream(ByteBuffer _bb) { return GetRootAsFBS_MoveComponentStream(_bb, new FBS_MoveComponentStream()); }
  public static FBS_MoveComponentStream GetRootAsFBS_MoveComponentStream(ByteBuffer _bb, FBS_MoveComponentStream obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyFBS_MoveComponentStream(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, FBS_MoveComponentStreamVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBS_MoveComponentStream __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public UIDocument.Script.Core.FBS.FBS_MoveComponent? MoveComponents(int j) { int o = __p.__offset(4); return o != 0 ? (UIDocument.Script.Core.FBS.FBS_MoveComponent?)(new UIDocument.Script.Core.FBS.FBS_MoveComponent()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int MoveComponentsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<UIDocument.Script.Core.FBS.FBS_MoveComponentStream> CreateFBS_MoveComponentStream(FlatBufferBuilder builder,
      VectorOffset move_componentsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FBS_MoveComponentStream.AddMoveComponents(builder, move_componentsOffset);
    return FBS_MoveComponentStream.EndFBS_MoveComponentStream(builder);
  }

  public static void StartFBS_MoveComponentStream(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddMoveComponents(FlatBufferBuilder builder, VectorOffset moveComponentsOffset) { builder.AddOffset(0, moveComponentsOffset.Value, 0); }
  public static VectorOffset CreateMoveComponentsVector(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateMoveComponentsVectorBlock(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMoveComponentsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateMoveComponentsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<UIDocument.Script.Core.FBS.FBS_MoveComponent>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartMoveComponentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<UIDocument.Script.Core.FBS.FBS_MoveComponentStream> EndFBS_MoveComponentStream(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<UIDocument.Script.Core.FBS.FBS_MoveComponentStream>(o);
  }
  public static void FinishFBS_MoveComponentStreamBuffer(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_MoveComponentStream> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFBS_MoveComponentStreamBuffer(FlatBufferBuilder builder, Offset<UIDocument.Script.Core.FBS.FBS_MoveComponentStream> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class FBS_MoveComponentStreamVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*MoveComponents*/, UIDocument.Script.Core.FBS.FBS_MoveComponentVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
